package com.example.agileandroidalpha.feature_board.presentation.add_edit_task

import com.example.agileandroidalpha.feature_board.domain.model.Subtask
import com.example.agileandroidalpha.feature_board.presentation.add_edit_task.components.TaskSubtaskData
import com.example.agileandroidalpha.firebase.firestore.model.FireUser
import com.example.agileandroidalpha.firebase.firestore.model.Story
import com.example.agileandroidalpha.firebase.firestore.model.SubTask

data class EditTaskState (
    var delta: Any = 0,
    var logo: Int? = null,
    var images: List<String>? = null,
    var subItem: SubTask? = null,
    var currentSub: Subtask? = null,
    var assUser: FireUser? = null,
    var repUser: FireUser? = null,
    var updateFlag: Boolean = false,
    var id: Long = -1,
    var taskId: Long = -1,
    var sid: Long = -1,
    var assId: Long = -1,
    var repId: Long = -1,
    var pid: Long = -1,
    var title: String = "",
    var body: String = "",
    var desc: String = "",
    var dod: String = "",
    var timestamp: Long = 0,
    var points: Long = 0,
    var priority: String = "",
    var color: Int = 0,
    var assignee: String = "",
    var assUid: String = "",
    var assUri: String = "",
    var reporter: String = "",
    var repUid: String = "",
    var repUri: String = "",
    var resolution: String = "Unresolved",
    var status: String = "TO DO",
    var done: Boolean = false,
    var labels: List<String> = emptyList(),
    var type: String = "Task",
    var typeIcon: Int? = null,
    var current: Boolean? = null,
    var active: Boolean? = null,
    var cloned: Boolean? = null,
    var subtasks: List<Long?>? = null,
    var numSubtasks: Int = 0,
    var timeToComplete: Long = 0,
    var project: String = "",
    var component: String = "",
    var versionsAffected: String? = "",
    var versionFixed: String = "",
    var environment: String = "",
    var log: List<String> = emptyList(),
    var comments: List<String> = emptyList(),
    var createdBy: String = "",
    var creatorID: Long = -1,
    var uidList: List<Long>? = null,
    var users: List<FireUser> = emptyList(),
    var stories: List<Story> = emptyList(),
    var subStates: List<TaskSubtaskData> = emptyList(),
    var me: FireUser? = null,
    var editTitle: String = "",
    var editDesc: String = "",
    var editBody: String = "",
    var editDoD: String = "",
    val uri: String? = null,
    val uid: String? = null,
){
}